# Generated by Django 5.0.2 on 2024-02-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('detail', models.CharField(max_length=255)),
                ('expired', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'voucher_entity',
            },
        ),
    ]
