# Generated by Django 5.0.2 on 2024-02-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherEntity',
        ),
    ]
