# Generated by Django 5.0.2 on 2024-02-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentManager', '0002_delete_voucherentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billdetailentity',
            old_name='item',
            new_name='item_list',
        ),
    ]
