# Generated by Django 5.0.2 on 2024-02-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountEntity', '0002_rename_is_admin_accountentity_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountentity',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
