# Generated by Django 5.0.2 on 2024-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountEntity', '0004_alter_accountentity_img_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('detail', models.CharField(max_length=255)),
                ('expired', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
