# Generated by Django 5.0.2 on 2024-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountEntity', '0005_alter_accountentity_email'),
        ('AccountEntity', '0005_voucherentity'),
    ]

    operations = [
    ]
