# Generated by Django 5.0.2 on 2024-02-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountEntity', '0006_merge_20240217_2258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountentity',
            table='account_entity',
        ),
        migrations.AlterModelTable(
            name='voucherentity',
            table='voucher_entity',
        ),
    ]
