# Generated by Django 5.0.2 on 2024-02-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_foodentity_status_alter_foodentity_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantentity',
            name='time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
