# Generated by Django 5.0.2 on 2024-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0003_alter_restaurantentity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantentity',
            name='star',
            field=models.FloatField(default=None, null=True),
        ),
    ]
