# Generated by Django 5.0.2 on 2024-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0004_alter_restaurantentity_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentity',
            name='star',
            field=models.FloatField(default=None, null=True),
        ),
    ]
