# Generated by Django 5.0.2 on 2024-02-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0006_alter_foodentity_quantity_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_by', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('food_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.foodentity')),
                ('restaurant_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductManager.restaurantentity')),
            ],
            options={
                'db_table': 'topping_entity',
            },
        ),
    ]
