# Generated by Django 5.0.2 on 2024-02-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0008_alter_foodentity_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentity',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='typefoodentity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
