# Generated by Django 5.0.2 on 2024-02-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0009_alter_foodentity_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantentity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
