# Generated by Django 5.0.2 on 2024-02-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0012_voucherentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherEntity',
        ),
    ]
