# Generated by Django 5.0.2 on 2024-02-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0013_alter_foodentity_quantity_purchased_and_more'),
        ('ProductManager', '0013_delete_voucherentity'),
    ]

    operations = [
    ]
