# Generated by Django 5.0.2 on 2024-02-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0014_merge_20240217_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentity',
            name='detail',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantentity',
            name='detail',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
